### ISSUE TITLE
Se possível, levar em consideração a criação de um auto complete

### ISSUE THREAD

**Issue by almeidaws** [mbakatsuki/stringchallenge#2]
- [x] Programar a interface do autocomplete.

Solução Local
- [x] Filtrar banco de dados para listar apenas os nomes das proteínas.
- [ ] Adicionar banco de dados das proteínas para fazer as buscas localmente.

Solução Assíncrona
- [x] Descobrir API para as sugestões de nomes
- [x] Realizar request após o usuário parar de digitar por um tempo.

**Comment by Felizolinha** [comment]
API para fazer o autocomplete por meio de requests: https://string-db.org/api/json/get_string_ids?identifiers=PTCH
