### ISSUE TITLE
Criar a cena de SpriteKit para apresentar de forma interativa e dinâmica as relações das proteínas

### ISSUE THREAD

**Issue by almeidaws** [mbakatsuki/stringchallenge#4]

**Comment by Felizolinha** [comment]
Podemos utilizar Force Directed Graphs pra desenhar os grafos, eles fazem uma simulação física e minimizam a energia do sistema pra posicionar os nós. O resultado é bem agradável, e é a mesma técnica utilizada pelo STRING Database para gerar as imagens deles.

Implementação em SpriteKit: https://github.com/joenot443/Spritekit-Force-Directed
